# Generated by Django 4.2.3 on 2023-07-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission',
            field=models.IntegerField(),
        ),
    ]
